version: '3'

services:
  db_dev:
    restart: always
    image: postgres
    container_name: core_dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=core_dev
    volumes:
      - pg:/data/postgres

volumes:
  pg:
    driver: local
