name: Elixir Build and Migrate
on: 
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]
env:
  MIX_ENV: test
  GUARDIAN_AUTH_TOKEN: ${{ secrets.GUARDIAN_AUTH_TOKEN }}

jobs:
  build:
    timeout-minutes: 7
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.3
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: core_dev

    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [25.0.0]
        elixir: [1.13.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Get Deps Cache
        uses: actions/cache@v2
        id: deps
        with:
          path: deps/
          key: ${{hashFiles('mix.lock')}}-deps

      - name: Get Build Cache
        uses: actions/cache@v2
        with:
          path: _build/
          key: ${{runner.os}}-${{hashFiles('mix.lock')}}-build

      - name: Get deps
        if: steps.deps.outputs.cache-hit != 'true'
        run: |
          mix deps.get

      - name: Install Dependencies
        run: |
          mix compile --warnings-as-errors

      - name: Migrate
        run: |
          mix ecto.create
          mix ecto.migrate